name: documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

jobs:
   docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinxcontrib-asyncio sphinx django numpy sphinx-copybutton sphinx-gallery nbsphinx sphinxcontrib-images
      - name: build
        run: |
           make html -C src
      - name: folder make
        run: |
           mkdir _build
      - name: copy
        run: |
           mv src/_build/* _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
          force_orphan: true
